#!/bin/bash
set -e

cmd/reset | true

printf "\n\e[0;32m🍣   Removing build folder...\e[0m\n\n"

rm -rf build
mkdir build
mkdir build/TEMP

printf "\n\e[0;32m🍣   Copying folders...\e[0m\n\n"

cp docs/favicon.ico build/favicon.ico
cp docs/_redirects build/_redirects

cp -r docs/images            build/
cp -r docs/icons             build/
cp -r docs/conference-logos  build/

printf "\n\e[0;32m🍣   Copying files...\e[0m\n\n"

cp docs/index.html  build/TEMP/index.html
node_modules/.bin/replace '(<script class="dev-only".*</script>)' '<!-- $1 -->' build/TEMP/index.html -m -i --silent
node_modules/.bin/replace '<!-- prod-only (.*) -->' '$1' build/TEMP/index.html -m -i --silent
node_modules/.bin/html-minifier -o build/index.html build/TEMP/index.html --remove-comments --collapse-whitespace --minify-css --minify-js --preserve-line-breaks
# Remove empy lines
node_modules/.bin/replace '^(?:[\t ]*(?:\r?\n|\r))+' '' build/index.html -m -i

cp build/index.html build/200.html


node_modules/.bin/uglifyjs docs/elm-starter.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=build/elm-starter.js

node_modules/.bin/elm make --output=build/TEMP/elm.js src/Main.elm --debug
node_modules/.bin/uglifyjs build/TEMP/elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=build/elm-with-debugger.js

node_modules/.bin/elm make --output=build/TEMP/elm.js src/Main.elm --optimize
node_modules/.bin/uglifyjs build/TEMP/elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | node_modules/.bin/uglifyjs --mangle --output=build/elm-without-debugger.js

printf "\n\e[0;32m🍣   Cleaning up...\e[0m\n\n"

rm -rf build/TEMP
